version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-discogs
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: discogs
      POSTGRES_PASSWORD: discogs
      POSTGRES_DB: discogs_db
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
